version: '3.1'

services:
  apache:
    image: php:7.4-apache
    container_name: docker-lamp-apache-server
    ports:
      - "8181:80"
    volumes:
      - ./www:/var/www/html

  mariadb:
    image: mariadb:latest
    container_name: docker-lamp-mariadb-server
    environment:
    # PATH: "/usr/lib/mysql:/etc/mysql:/usr/share/mysql:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      PATH: "/usr/lib/mysql:/usr/bin/mariadb:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: DockerMySQLTest
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3366:3306"
    # command: bash -c "docker-entrypoint.sh mysqld & /docker-entrypoint-initdb.d/mariadb-verify.sh"
    # entrypoint: ["sh", "entrypoint.sh"]
   volumes:
    - ./db:/docker-entrypoint-initdb.d
networks:
  lamp-network:
    driver: bridge

